services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  simple-flask-app: 
    image: gokulviswanathan/flask-views-counter:1.1
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - 8080:8080
    environment:
      - FLASK_APP=app.py
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy