services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  simple-flask-app: 
    build: ./simple-webapp-flask
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - 5000:8000
    environment:
      - FLASK_APP=app.py
    env_file:
      - ./simple-webapp-flask/env.list
    depends_on:
      db:
        condition: service_healthy